### ISSUE TITLE
Error Acquiring Token: Microsoft.Identity.Client.MsalServiceException: AADB2C90079: Clients must send a client_secret when redeeming a confidential grant.

### ISSUE THREAD

**Issue by aarondglover** [Azure-Samples/active-directory-b2c-dotnet-desktop#21]
When Attempting to Sign-In I receive the following Error.

```
Error Acquiring Token:
Microsoft.Identity.Client.MsalServiceException: AADB2C90079: Clients must send a client_secret when redeeming a confidential grant.
Correlation ID: 12179f8b-25b5-4e26-a8be-2357a203af36
Timestamp: 2019-04-04 23:21:40Z

   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateErrorResponse(HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext, Boolean addCorrelationId)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.<ExecuteRequestAsync>d__10'1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.<GetTokenAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<SendHttpMessageAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<SendTokenRequestAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<ExecuteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.PublicClientApplication.<AcquireTokenForUserCommonAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.PublicClientApplication.<AcquireTokenAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter'1.GetResult()
   at active_directory_b2c_wpf.MainWindow.<SignInButton_Click>d__1.MoveNext() in C:\Users\r\source\repos\active-directory-b2c-dotnet-desktop-master\active-directory-b2c-wpf\MainWindow.xaml.cs:line 34
	ErrorCode: invalid_request
	StatusCode: 400
	Claims: 
```

Please Help. Has some sort of token expired which I need to refresh?

**Comment by jmprieur** [comment]
if this was AAD, the app registration would require you to set the **Default Client Type** to **Yes**, but here this is B2C. @valnav : is there the same equivalent for the B2C app registration?

![image](https://user-images.githubusercontent.com/13203188/55599854-e0660900-5759-11e9-8891-0e35de8d8d25.png)

**Comment by jennyf19** [comment]
@aarondglover Are you still having this issue?

**Comment by roycornelissen** [comment]
@jennyf19  I'm now facing this issue (from a .NET Core Console app) against B2C. Any new insight on how to deal with this?

**Comment by jennyf19** [comment]
@roycornelissen did you see what @jmprieur posted above about checking "Default client type to public client" in the portal?

**Comment by roycornelissen** [comment]
@jennyf19 I would if I could find the setting... The app registration was made in B2C, no "Default client type to public client" setting there, and when I look it up from the AAD pane, the setting is also not there. Unless it's a Premium feature? (not using Azure AD Premium)

**Comment by jennyf19** [comment]
@roycornelissen I don't believe this is a premium feature. If you are in AAD, you should be able to see it when you click on "Authentication" in your app registration (@jmprieur has included a screen shot above). You will want to be in the new registration experience, not the legacy one.

For B2C, you are right, I do not see an option for this, and also not in the manifest. For AAD, you should see something like this in the manifest:

`"allowPublicClient": true,`

Will follow up w/B2C today and update here w/any findings.

**Comment by jennyf19** [comment]
@roycornelissen Actually, in the B2C app manifest, there is a field for `"publicClient":true`

Do you want to edit the manifest and see if that resolves the issues (at least temporarily)? 
![image](https://user-images.githubusercontent.com/19942418/61144118-db1b0780-a488-11e9-9b19-0dfdbebfdb5b.png)

**Comment by jmprieur** [comment]
@valnav @parakhj can we please have your guidance for this issue. How to register the B2C app?

**Comment by roycornelissen** [comment]
@jennyf19 Thanks for hints... OK, I did find the "Default client type to public client" setting after all... There seem to be **four** different ways (for me at least) to go to application registrations in the portal... 

1. Through _Active Directory > Enterprise Applications_
2. _Azure Active Directory > App registrations (Legacy)_, 
3. through the _Azure AD B2C > Applications_, 
4. and finally - when I just search for "App Registrations" in the home page of the portal (I am taken to https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade).

It's in this latter page where I can find the "Default client type to public client" setting. Each version of App registrations shows different apps and different properties. Very, very confusing...

Anyway, I now believe that my error message has to do with MSAL, or the way I use it. I have verified that  "Default client type to public client"  is set to true, and have tried authentication in both a WPF client app, which uses an embedded browser window and my Console App, which uses the default browser because it doesn't have any parent window. Otherwise, both of them are setup the same way, using the `PublicClientApplication` API. 

The WPF app succeeds in authenticating and I can use the token, the Console app fails with the `Error Acquiring Token: Microsoft.Identity.Client.MsalServiceException: AADB2C90079: Clients must send a client_secret when redeeming a confidential grant.` message.

@jmprieur I just registered these apps through the B2C portal's _Applications_ pane, as I cannot see them otherwise and use them in any B2C user flow.

**Comment by jennyf19** [comment]
@roycornelissen I will share the feedback with the B2C portal team. 

Can you share the code you are using for creating the public client and for the acquire token call?

**Comment by roycornelissen** [comment]
@jennyf19 Sure... the actual application is a little bit more elaborate, but this is it in essence: https://gist.github.com/roycornelissen/7eafb17b27485933c1d15d942d7e26b6

With this code, I can reproduce the problem. On Windows, the authentication in the browser (Edge) completes, but with the `AADB2C90079` error. I also tried running it on my Mac, but in Safari, the login page doesn't even seem to submit the credentials, so the whole flow doesn't even work :(

**Comment by jmprieur** [comment]
@valnav @parakhj FYI

**Comment by assafsl** [comment]
Has this been resolved? Having the same issue here

**Comment by mmacy** [comment]
Hi @assafsl, curious if you've followed the steps these two articles--you should not encounter this issue, if so:

* [Tutorial: Authenticate users in a native desktop client using Azure AD B2C](https://docs.microsoft.com/azure/active-directory-b2c/active-directory-b2c-tutorials-desktop-app?tabs=app-reg-preview)
* [Tutorial: Grant access to a Node.js web API from a desktop app using Azure AD B2C](https://docs.microsoft.com/azure/active-directory-b2c/active-directory-b2c-tutorials-desktop-app-webapi?tabs=app-reg-preview)

> NOTE: Those links should set the default of the tabs in the article to the new **App registrations (preview)** experience. You can use the current *Applications* registration experience if you prefer, however.

**Comment by mmacy** [comment]
@assafsl Also, if you need to enable public client in a registered B2C application:

1. Navigate to your B2C tenant
1. Select **App registrations (preview)**
1. Select your application
1. Select **Authentication**
1. Select **Try out the new experience**
1. Under **Advanced** > **Default client type** > **Treat  application as a public client** select **Yes**.

![image](https://user-images.githubusercontent.com/13394541/70077744-425f6280-15b6-11ea-97f6-773bf4cfde32.png)

**Comment by assafsl** [comment]
Thank you @mmacy I solved the problem by choosing "Public client/ native (mobile & desktop) as the type of the redirect URI of my app.

I missed correlation between _Web/ Public_ and _PublicClientApplication/ ConfidentialClientApplication_ 
![image](https://user-images.githubusercontent.com/17673532/70079373-4bc7e980-160d-11ea-9f89-905b67901400.png)

**Comment by sorenhoyer** [comment]
They really should make it more clear that browser/client-only frontend apps that wants to use the Authorization Code flow with PKCE will need this "Treat application as a public client" enabled :-)
